I'm sorry, but an uncaught exception occurred.

While loading the script.
ScriptError: Name ('game/classScripts/Login.rpy', 1746368040, 0) is defined twice, at game/classScripts/Login.rpy:1 and game/classScripts/Login.rpy:1.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-8.3.6-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\renpy-8.3.6-sdk\renpy\main.py", line 470, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "D:\renpy-8.3.6-sdk\renpy\script.py", line 359, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "D:\renpy-8.3.6-sdk\renpy\script.py", line 957, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn) # type: ignore
  File "D:\renpy-8.3.6-sdk\renpy\script.py", line 590, in finish_load
    check_name(node)
  File "D:\renpy-8.3.6-sdk\renpy\script.py", line 566, in check_name
    raise ScriptError("Name %s is defined twice, at %s:%d and %s:%d." %
ScriptError: Name ('game/classScripts/Login.rpy', 1746368040, 0) is defined twice, at game/classScripts/Login.rpy:1 and game/classScripts/Login.rpy:1.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.6.25022803
 
Sun May  4 21:14:00 2025
